import type { User, AttendanceRecord, FieldVisit, LeaveRequest } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Mahadev Sharma',
    email: 'admin@mahadevent.com',
    phone: '+91 98765 43210',
    role: 'ADMIN',
    department: 'Executive Management',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-2',
    name: 'Rajesh Verma',
    email: 'rajesh.v@mahadevent.com',
    phone: '+91 98123 45678',
    role: 'MANAGER',
    department: 'Field Operations',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-3',
    name: 'Amit Patel',
    email: 'amit.p@mahadevent.com',
    phone: '+91 97234 56789',
    role: 'FIELD_EXEC',
    department: 'Sales & Field Service',
    managerId: 'usr-2',
    managerName: 'Rajesh Verma',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-4',
    name: 'Priya Sundaram',
    email: 'priya.s@mahadevent.com',
    phone: '+91 96345 67890',
    role: 'FIELD_EXEC',
    department: 'Sales & Field Service',
    managerId: 'usr-2',
    managerName: 'Rajesh Verma',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-5',
    name: 'Suresh Kumar',
    email: 'suresh.k@mahadevent.com',
    phone: '+91 95456 78901',
    role: 'STAFF',
    department: 'Backoffice & Support',
    managerId: 'usr-2',
    managerName: 'Rajesh Verma',
    status: 'ACTIVE',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-101',
    userId: 'usr-3',
    userName: 'Amit Patel',
    userRole: 'FIELD_EXEC',
    date: new Date().toISOString().split('T')[0],
    punchInTime: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    punchInLocation: {
      lat: 19.076,
      lng: 72.8777,
      address: 'Andheri East Industrial Hub, Mumbai',
    },
    status: 'ON_FIELD',
    workMode: 'FIELD',
    notes: 'Starting client visits for industrial equipment check',
  },
  {
    id: 'att-102',
    userId: 'usr-4',
    userName: 'Priya Sundaram',
    userRole: 'FIELD_EXEC',
    date: new Date().toISOString().split('T')[0],
    punchInTime: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    punchInLocation: {
      lat: 19.1197,
      lng: 72.9051,
      address: 'Powai Business District, Mumbai',
    },
    status: 'PRESENT',
    workMode: 'FIELD',
    notes: 'On-site audit visit at Powai client site',
  },
  {
    id: 'att-103',
    userId: 'usr-5',
    userName: 'Suresh Kumar',
    userRole: 'STAFF',
    date: new Date().toISOString().split('T')[0],
    punchInTime: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    punchInLocation: {
      lat: 19.0176,
      lng: 72.8561,
      address: 'Mahadev HQ Office, Dadar, Mumbai',
    },
    status: 'PRESENT',
    workMode: 'OFFICE',
  },
];

export const INITIAL_FIELD_VISITS: FieldVisit[] = [
  {
    id: 'vst-201',
    title: 'Solar Panel Maintenance Audit & Call',
    clientName: 'Apex Logistics & Warehousing',
    clientPhone: '+91 98200 11223',
    clientAddress: 'Plot 45, Bhiwandi Industrial Zone, Thane',
    targetLocation: { lat: 19.2812, lng: 73.0489 },
    assignedToId: 'usr-3',
    assignedToName: 'Amit Patel',
    assignedById: 'usr-2',
    assignedByName: 'Rajesh Verma',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '11:30',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    checkInTime: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    checkInLocation: {
      lat: 19.2815,
      lng: 73.0491,
      address: 'Gate 2, Bhiwandi Logistics Park',
    },
    summaryNotes: 'Inspected inverter battery bank. Replaced blown fuse in Unit B.',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'vst-202',
    title: 'New Client Demo & Product Pitch',
    clientName: 'Zenith Tech Solutions',
    clientPhone: '+91 99300 44556',
    clientAddress: '7th Floor, Trade Tower, Bandra Kurla Complex',
    targetLocation: { lat: 19.0657, lng: 72.8687 },
    assignedToId: 'usr-4',
    assignedToName: 'Priya Sundaram',
    assignedById: 'usr-2',
    assignedByName: 'Rajesh Verma',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '14:00',
    priority: 'URGENT',
    status: 'ASSIGNED',
    createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'vst-203',
    title: 'Quarterly Service Contract Renewal',
    clientName: 'Global Hospital Infrastructure',
    clientPhone: '+91 98111 22334',
    clientAddress: 'Sector 15, Vashi, Navi Mumbai',
    targetLocation: { lat: 19.0771, lng: 72.9986 },
    assignedToId: 'usr-3',
    assignedToName: 'Amit Patel',
    assignedById: 'usr-1',
    assignedByName: 'Mahadev Sharma',
    scheduledDate: new Date().toISOString().split('T')[0],
    scheduledTime: '16:30',
    priority: 'MEDIUM',
    status: 'ASSIGNED',
    createdAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
  {
    id: 'vst-204',
    title: 'Emergency Generator Inspection',
    clientName: 'Reliance Fresh Logistics Hub',
    clientPhone: '+91 97777 88899',
    clientAddress: 'Kalamboli Warehouse Complex, Navi Mumbai',
    targetLocation: { lat: 19.034, lng: 73.109 },
    assignedToId: 'usr-4',
    assignedToName: 'Priya Sundaram',
    assignedById: 'usr-2',
    assignedByName: 'Rajesh Verma',
    scheduledDate: new Date(Date.now() - 24 * 3600 * 1000).toISOString().split('T')[0],
    scheduledTime: '10:00',
    priority: 'HIGH',
    status: 'COMPLETED',
    checkInTime: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    checkOutTime: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    summaryNotes: 'Generators tested under load. Fuel filters changed. Client satisfied.',
    rating: 5,
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lev-301',
    userId: 'usr-3',
    userName: 'Amit Patel',
    startDate: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString().split('T')[0],
    endDate: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString().split('T')[0],
    leaveType: 'CASUAL',
    reason: 'Family event in hometown',
    status: 'PENDING',
    createdAt: new Date().toISOString(),
  },
];
